# Generated by Django 5.0 on 2026-05-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_maintenance',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_ac',
            field=models.BooleanField(default=True, verbose_name='AC Available'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_breakfast',
            field=models.BooleanField(default=False, verbose_name='Free Breakfast'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=True, verbose_name='Free Parking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Swimming Pool'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='hotels/default.jpg', upload_to='hotels/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Trending/Popular Stay'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hotels.hotel'),
        ),
    ]
