# Generated by Django 5.0 on 2026-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_roomcategory_options_remove_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
